name: Build WARP Desktop

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:linux
        env:
          GH_TOKEN: ""
          PUBLISH_FOR_PULL_REQUEST: "false"
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:win
        env:
          GH_TOKEN: ""
          PUBLISH_FOR_PULL_REQUEST: "false"
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            !dist/win-unpacked/**
